# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Define our matrix of build configurations to test against.
matrix:
  include:
   - php: 5.2
     env: WP_VERSION=4.4 WC_VERSION=2.6.14
     sudo: true
     dist: precise
   - php: 5.2
     env: WP_VERSION=latest WC_VERSION=3.3.3
     sudo: true
     dist: precise
   - php: 5.3
     env: WP_VERSION=4.5 WC_VERSION=3.2.6
     sudo: true
     dist: precise
   - php: 5.4
     env: WP_VERSION=4.6 WC_VERSION=3.1.2
   - php: 5.5
     env: WP_VERSION=4.7 WC_VERSION=3.0.9
   - php: 5.6
     env: WP_VERSION=4.8 WC_VERSION=2.6.14
   - php: 7.0
     env: WP_VERSION=latest WC_VERSION=2.6.14
   - php: 7.1
     env: WP_VERSION=latest WC_VERSION=3.0.3
   - php: 7.2
     env: WP_VERSION=4.4 WC_VERSION=2.6.14
   - php: 7.2
     env: WP_VERSION=latest WC_VERSION=3.3.3
     # Run the JS tests in a separate container
   - language: node_js
     before_script: ""

# Clones WordPress and configures our testing environment.
before_script: bash tests/bin/install-wc-tests.sh wordpress_test root '' localhost $WP_VERSION $WC_VERSION

sudo: false

notifications:
   email:
       - hydra@matticspace.com
