# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Next we define our matrix of build configurations to test against.

matrix:
  include:
   - php: 5.2
     env: WP_VERSION=4.4 WC_VERSION=2.6.14
     sudo: true
     dist: precise
   - php: 5.2
     env: WP_VERSION=latest WC_VERSION=3.3.3
     sudo: true
     dist: precise
   - php: 5.3
     env: WP_VERSION=4.5 WC_VERSION=3.2.6
     sudo: true
     dist: precise
   - php: 5.4
     env: WP_VERSION=4.6 WC_VERSION=3.1.2
   - php: 5.5
     env: WP_VERSION=4.7 WC_VERSION=3.0.9
   - php: 5.6
     env: WP_VERSION=4.8 WC_VERSION=2.6.14
   - php: 7.0
     env: WP_VERSION=latest WC_VERSION=2.6.14
   - php: 7.1
     env: WP_VERSION=latest WC_VERSION=3.0.3
   - php: 7.2
     env: WP_VERSION=4.4 WC_VERSION=2.6.14
   - php: 7.2
     env: WP_VERSION=latest WC_VERSION=3.3.3

# Cache the NPM dependencies
cache:
  directories:
    - node_modules
    - "$HOME/.nvm"

# Use an updated Node runtime
# See: http://entulho.fiatjaf.alhur.es/guias/how-to-use-node-along-with-other-language-on-travis-ci/
install:
    - . $HOME/.nvm/nvm.sh
    - nvm install 8.9.3
    - nvm use 8.9.3
    - npm install

# Clones WordPress and configures our testing environment.
before_script:
    - bash tests/bin/install-wc-tests.sh wordpress_test root '' localhost $WP_VERSION $WC_VERSION

script: phpunit && npm test

sudo: false

notifications:
   email:
       - hydra@matticspace.com
