name: E2E Tests

on: [push, workflow_dispatch]

jobs:
  e2e_build_and_test:
    name: Build Container and Run E2E Tests
    runs-on: ubuntu-18.04
    env:
      WP_VERSION: 5.6
      TRAVIS_MARIADB_VERSION: 10.5.5
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '10.16.0'
#      - run: composer self-update 2.0.6 && composer install --no-progress
      - run: npm ci
      - run: npm install jest --global
      - run: npm run docker:up
      - run: npm run docker:ping
      - run: npm run test:e2e
      - run: npm run docker:down
