name: E2E Tests

on: [push, workflow_dispatch]

jobs:
  e2e_build_and_test:
    name: Build Container and Run E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wp-version: [5.6, latest]
    env:
      WP_VERSION: ${{ matrix.wp-version }}
      TRAVIS_MARIADB_VERSION: 10.5.5
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '10.16.0'
      - run: npm ci
      - run: npm install jest --global
      - run: |
             sudo systemctl stop mono-xsp4.service || true
             sudo systemctl disable mono-xsp4.service || true
      - run: npm run docker:up
      - run: npm run docker:ping
      - run: npm run test:e2e
      - run: npm run docker:down
