name: JS Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  js_build_and_test:
    name: JS Estlin and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm ci
      - run: npm run eslint
      - run: npm run test