name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  js_build_and_test:
    name: JS Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm ci
      - run: npm run eslint
      - run: npm run test
  php_build_and_test:
    name: PHP Build and Test
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: wp_test
          MYSQL_PASSWORD: wp_test
          MYSQL_DATABASE: wordpress_test
          MYSQL_ROOT_PASSWORD:
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: tests/bin/install-wc-tests.sh wordpress_test root '' 127.0.0.1 5.6.2 5.0.0
      - run: curl -sSfL -o ~/.phpenv/versions/7.2/bin/phpunit https://phar.phpunit.de/phpunit-6.4.phar && phpunit
